const countries = [
  {"value":0,"label":"أفغانستان"},
  {"value":1,"label":"ألبانيا"},
  {"value":2,"label":"الجزائر"},
  {"value":3,"label":"أندورا"},
  {"value":4,"label":"أنغولا"},
  {"value":5,"label":"أنتيغوا وباربودا"},
  {"value":6,"label":"الأرجنتين"},
  {"value":7,"label":"أرمينيا"},
  {"value":8,"label":"أستراليا"},
  {"value":9,"label":"النمسا"},
  {"value":10,"label":"أذربيجان"},
  {"value":11,"label":"باهاماس"},
  {"value":12,"label":"البحرين"},
  {"value":13,"label":"بنغلاديش"},
  {"value":14,"label":"باربادوس"},
  {"value":15,"label":"بيلاروس"},
  {"value":16,"label":"بلجيكا"},
  {"value":17,"label":"بليز"},
  {"value":204,"label":"بنين"},
  {"value":64,"label":"بوتان"},
  {"value":68,"label":"بوليفيا"},
  {"value":70,"label":"البوسنة والهرسك"},
  {"value":72,"label":"بوتسوانا"},
  {"value":76,"label":"البرازيل"},
  {"value":96,"label":"بروناي"},
  {"value":100,"label":"بلغاريا"},
  {"value":854,"label":"بوركينا فاسو"},
  {"value":108,"label":"بوروندي"},
  {"value":116,"label":"كمبوديا"},
  {"value":120,"label":"الكاميرون"},
  {"value":124,"label":"كندا"},
  {"value":132,"label":"الرأس الأخضر"},
  {"value":140,"label":"جمهورية أفريقيا الوسطى"},
  {"value":148,"label":"تشاد"},
  {"value":152,"label":"تشيلي"},
  {"value":156,"label":"الصين"},
  {"value":170,"label":"كولومبيا"},
  {"value":174,"label":"جزر القمر"},
  {"value":178,"label":"جمهورية الكونغو"},
  {"value":180,"label":"جمهورية الكونغو الديمقراطية"},
  {"value":188,"label":"كوستاريكا"},
  {"value":384,"label":"ساحل العاج"},
  {"value":191,"label":"كرواتيا"},
  {"value":192,"label":"كوبا"},
  {"value":196,"label":"قبرص"},
  {"value":203,"label":"جمهورية التشيك"},
  {"value":208,"label":"الدنمارك"},
  {"value":262,"label":"جيبوتي"},
  {"value":212,"label":"دومينيكا"},
  {"value":214,"label":"جمهورية الدومينيكان"},
  {"value":218,"label":"الإكوادور"},
  {"value":818,"label":"مصر"},
  {"value":222,"label":"السلفادور"},
  {"value":226,"label":"غينيا الاستوائية"},
  {"value":232,"label":"إريتريا"},
  {"value":233,"label":"إستونيا"},
  {"value":231,"label":"إثيوبيا"},
  {"value":242,"label":"فيجي"},
  {"value":246,"label":"فنلندا"},
  {"value":250,"label":"فرنسا"},
  {"value":266,"label":"الغابون"},
  {"value":270,"label":"غامبيا"},
  {"value":268,"label":"جورجيا"},
  {"value":276,"label":"ألمانيا"},
  {"value":288,"label":"غانا"},
  {"value":300,"label":"اليونان"},
  {"value":308,"label":"غرينادا"},
  {"value":320,"label":"غواتيمالا"},
  {"value":324,"label":"غينيا"},
  {"value":624,"label":"غينيا بيساو"},
  {"value":328,"label":"غيانا"},
  {"value":332,"label":"هايتي"},
  {"value":340,"label":"هندوراس"},
  {"value":348,"label":"المجر"},
  {"value":352,"label":"آيسلندا"},
  {"value":356,"label":"الهند"},
  {"value":360,"label":"إندونيسيا"},
  {"value":364,"label":"إيران"},
  {"value":368,"label":"العراق"},
  {"value":372,"label":"أيرلندا"},
  {"value":376,"label":"إسرائيل"},
  {"value":380,"label":"إيطاليا"},
  {"value":388,"label":"جامايكا"},
  {"value":392,"label":"اليابان"},
  {"value":400,"label":"الأردن"},
  {"value":398,"label":"كازاخستان"},
  {"value":404,"label":"كينيا"},
  {"value":296,"label":"كيريباتي"},
  {"value":408,"label":"كوريا الشمالية"},
  {"value":410,"label":"كوريا الجنوبية"},
  {"value":414,"label":"الكويت"},
  {"value":417,"label":"قيرغيزستان"},
  {"value":418,"label":"لاوس"},
  {"value":428,"label":"لاتفيا"},
  {"value":422,"label":"لبنان"},
  {"value":426,"label":"ليسوتو"},
  {"value":430,"label":"ليبيريا"},
  {"value":434,"label":"ليبيا"},
  {"value":438,"label":"ليختنشتاين"},
  {"value":440,"label":"ليتوانيا"},
  {"value":442,"label":"لوكسمبورغ"},
  {"value":807,"label":"مقدونيا"},
  {"value":450,"label":"مدغشقر"},
  {"value":454,"label":"مالاوي"},
  {"value":458,"label":"ماليزيا"},
  {"value":462,"label":"جزر المالديف"},
  {"value":466,"label":"مالي"},
  {"value":470,"label":"مالطا"},
  {"value":584,"label":"جزر مارشال"},
  {"value":478,"label":"موريتانيا"},
  {"value":480,"label":"موريشيوس"},
  {"value":484,"label":"المكسيك"},
  {"value":583,"label":"ولايات ميكرونيسيا المتحدة"},
  {"value":504,"label":"المغرب"},
  {"value":498,"label":"مولدوفا"},
  {"value":492,"label":"موناكو"},
  {"value":496,"label":"منغوليا"},
  {"value":499,"label":"الجبل الأسود"},
  {"value":508,"label":"موزمبيق"},
  {"value":104,"label":"ميانمار"},
  {"value":516,"label":"ناميبيا"},
  {"value":520,"label":"ناورو"},
  {"value":524,"label":"نيبال"},
  {"value":528,"label":"هولندا"},
  {"value":554,"label":"نيوزيلندا"},
  {"value":558,"label":"نيكاراغوا"},
  {"value":562,"label":"النيجر"},
  {"value":566,"label":"نيجيريا"},
  {"value":578,"label":"النرويج"},
  {"value":512,"label":"عمان"},
  {"value":586,"label":"باكستان"},
  {"value":585,"label":"بالاو"},
  {"value":591,"label":"بنما"},
  {"value":598,"label":"بابوا غينيا الجديدة"},
  {"value":600,"label":"باراغواي"},
  {"value":604,"label":"بيرو"},
  {"value":608,"label":"الفلبين"},
  {"value":616,"label":"بولندا"},
  {"value":620,"label":"البرتغال"},
  {"value":634,"label":"قطر"},
  {"value":642,"label":"رومانيا"},
  {"value":643,"label":"روسيا"},
  {"value":646,"label":"رواندا"},
  {"value":659,"label":"سانت كيتس ونيفيس"},
  {"value":662,"label":"سانت لوسيا"},
  {"value":670,"label":"سانت فينسنت والغرينادين"},
  {"value":882,"label":"ساموا"},
  {"value":674,"label":"سان مارينو"},
  {"value":678,"label":"ساو تومي وبرينسيب"},
  {"value":682,"label":"السعودية"},
  {"value":686,"label":"السنغال"},
  {"value":688,"label":"صربيا"},
  {"value":690,"label":"سيشل"},
  {"value":694,"label":"سيراليون"},
  {"value":702,"label":"سنغافورة"},
  {"value":703,"label":"سلوفاكيا"},
  {"value":705,"label":"سلوفينيا"},
  {"value":90,"label":"جزر سليمان"},
  {"value":706,"label":"الصومال"},
  {"value":710,"label":"جنوب أفريقيا"},
  {"value":728,"label":"جنوب السودان"},
  {"value":724,"label":"إسبانيا"},
  {"value":144,"label":"سريلانكا"},
  {"value":729,"label":"السودان"},
  {"value":740,"label":"سورينام"},
  {"value":748,"label":"إسواتيني"},
  {"value":752,"label":"السويد"},
  {"value":756,"label":"سويسرا"},
  {"value":760,"label":"سوريا"},
  {"value":762,"label":"طاجيكستان"},
  {"value":834,"label":"تنزانيا"},
  {"value":764,"label":"تايلاند"},
  {"value":626,"label":"تيمور الشرقية"},
  {"value":768,"label":"توغو"},
  {"value":776,"label":"تونغا"},
  {"value":780,"label":"ترينيداد وتوباغو"},
  {"value":788,"label":"تونس"},
  {"value":792,"label":"تركيا"},
  {"value":795,"label":"تركمانستان"},
  {"value":798,"label":"توفالو"},
  {"value":800,"label":"أوغندا"},
  {"value":804,"label":"أوكرانيا"},
  {"value":784,"label":"الإمارات العربية المتحدة"},
  {"value":826,"label":"المملكة المتحدة"},
  {"value":840,"label":"الولايات المتحدة"},
  {"value":858,"label":"الأوروغواي"},
  {"value":860,"label":"أوزبكستان"},
  {"value":548,"label":"فانواتو"},
  {"value":862,"label":"فنزويلا"},
  {"value":704,"label":"فيتنام"},
  {"value":887,"label":"اليمن"},
  {"value":894,"label":"زامبيا"},
  {"value":716,"label":"زيمبابوي"},
  {"value":999,"label":"فلسطين"}
  ]
  
  export default countries;